### ISSUE TITLE
NoMethodError: undefined method `alpn_select_cb=' for #<OpenSSL::SSL::SSLContext:0x00007fab480133f8>

### ISSUE THREAD

**Issue by sorgal** [socketry/falcon#100]
I created new app, replaced puma with falcon. And when I'm starting falcon server, it raises this error:

`0.1s    error: Async::Task [oid=0x143c] [pid=13400] [2020-02-19 17:02:53 +0300]`
`NoMethodError: undefined method `alpn_select_cb=' for` #`<`OpenSSL::SSL::SSLContext:0x0000000001675b00`>`

`Did you mean?  npn_select_cb=`
                          `npn_select_cb`

Backtrace:
`→ /home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/falcon-0.35.3/lib/falcon/endpoint.rb:36 in `block in `build_ssl_context'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/falcon-0.35.3/lib/falcon/endpoint.rb:35 in `tap'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/falcon-0.35.3/lib/falcon/endpoint.rb:35 in `build_ssl_context'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/falcon-0.35.3/lib/falcon/endpoint.rb:29 in `ssl_context'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-http-0.50.2/lib/async/http/endpoint.rb:183 in `build_endpoint'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-http-0.50.2/lib/async/http/endpoint.rb:64 in `initialize'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-http-0.50.2/lib/async/http/endpoint.rb:208 in `new'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-http-0.50.2/lib/async/http/endpoint.rb:208 in `block in each'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-io-1.27.3/lib/async/io/host_endpoint.rb:90 in `block in each'`

`/home/sorgal/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/socket.rb:227 in `each'`

`/home/sorgal/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/socket.rb:227 in `foreach'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-io-1.27.3/lib/async/io/host_endpoint.rb:89 in `each'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-http-0.50.2/lib/async/http/endpoint.rb:207 in `each'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-io-1.27.3/lib/async/io/endpoint.rb:102 in `bound'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-io-1.27.3/lib/async/io/shared_endpoint.rb:31 in `bound'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/falcon-0.35.3/lib/falcon/controller/serve.rb:59 in `block in start'`

`/home/sorgal/.rvm/gems/ruby-2.7.0@falcon_test_app/gems/async-1.24.2/lib/async/task.rb:258 in `block in make_fiber'`

**Comment by olleolleolle** [comment]
Background notes: It can be that the running Ruby extension (called `openssl`) was compiled in such a way that [ALPN](https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation) support was not included.

https://github.com/ruby/openssl/blob/4a7249e83a5095a3910378ba1113b54a52344dbd/ext/openssl/ossl_ssl.c#L2742

**Comment by ioquatix** [comment]
You need to update your version of openssl to something not ancient, then you will need to reinstall Ruby because the OpenSSL gem itself is compiled against whatever version you had available at the time.

**Comment by ioquatix** [comment]
If doing that doesn't fix your issue please let me know :)
