### ISSUE TITLE
Need the ability to turn off SSL

### ISSUE THREAD

**Issue by joekhoobyar** [socketry/falcon#103]
I need the ability to turn off SSL - both for local testing (I'm on Catalina, and the self-signed cert creates issues) and for running in kubernetes (I will use cert-manager to manage SSL).

Is this something that can be done via an environment variable?  I can't do it via a CLI option, AFAIK.

**Comment by ioquatix** [comment]
`falcon serve --bind http://localhost`

**Comment by joekhoobyar** [comment]
Sweet.  Any chance of getting `falcon` to work with `rerun`?  I know it's a separate topic, I can open a separate bug ticket for it.
