### ISSUE TITLE
Ability to run falcon using rerun (to enable auto-reloading of code)

### ISSUE THREAD

**Issue by joekhoobyar** [socketry/falcon#104]
What I want to do is:

`rerun -- falcon serve --bind http://localhost:9292`

It works on initial launch, but when I modify my code (triggering `rerun`), I get an error:

`/usr/local/lib/ruby/gems/2.5.0/gems/async-io-1.27.3/lib/async/io/socket.rb:160:in `bind': Address already in use - bind(2) for [::1]:9292 (Errno::EADDRINUSE)`

It seems that, somehow, even though rerun is sending a `TERM` signal, the address is kept open.  Is there a deeper child process in the process tree that `rerun` is unable to send a signal to?

**Comment by ioquatix** [comment]
What OS are you running on?

**Comment by joekhoobyar** [comment]
For local development, Mac OS Catalina.  When I push this out to my home lab - I won't be using `rerune`... but the deployment will be on kubernetes running on "metal" Gentoo (amd64) or Arch (armv7l)

**Comment by ioquatix** [comment]
I think there are timeouts w.r.t. socket reuse which might be causing issues. I tried on Linux and could not reproduce the issue. I have a macos laptop so I can try there too.

That being said, it would probably make more sense to use a custom signal to reload the client app. Can `rerun` send any signal?

**Comment by joekhoobyar** [comment]
`rerun` can send any signal, but for proper code reloading wouldn't it need to stop / start `falcon` regardless?

**Comment by ioquatix** [comment]
```
  0.2s     info: Falcon::Endpoint [oid=0x3fd22e51fe10] [pid=82867] [2020-03-05 09:32:09 +1300]
               | Falcon v0.35.1 taking flight! Using Async::Container::Forked {:count=>8}.
               | - To terminate: Ctrl-C or kill 82867
               | - To reload configuration: kill -HUP 82867
```

Try using SIGHUP.

Although I'm not certain `falcon serve` completely reloads all library code (e.g. gems that have been loaded into the process) in that case, but at least it should be an improvement.

It certainly makes sense for us to support this use case better, but can you try that to start with?

**Comment by ioquatix** [comment]
The next release of falcon should make this use-case even better, since falcon serve will also support preloading and per-container app instances (rather than a shared instance). So, it will make reloading more clean.

**Comment by osbre** [comment]
Any news on this? I'm using Sinatra and wondering if there are ways to achieve hot reload with Falcon

**Comment by ioquatix** [comment]
Falcon supports live reloading by sending SIGINT.

Any command that can do that is sufficient:

I created a gem for my own use:

```
> io-watch pages -- bundle exec falcon serve --bind http://localhost:3000 --count 1
```

If you combine this with the `live` gem you can also reload the page you are looking at - I'll release more detailed instructions of how to do this later.
