### ISSUE TITLE
Establishing websocket connection in Rails app using ActionCable causes error

### ISSUE THREAD

**Issue by deepj** [socketry/falcon#106]
```
Started GET "/cable" for ::1 at 2020-03-13 10:03:58 +0100
Started GET "/cable/" [WebSocket] for ::1 at 2020-03-13 10:03:58 +0100
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for ::1 at 2020-03-13 10:03:59 +0100
 9m12s    error: Async::Task [oid=0xd9a8] [pid=42462] [2020-03-13 10:03:59 +0100]
               |   Errno::EPIPE: Broken pipe
               |   → <internal:io> 121
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.3/lib/async/io/generic.rb:216 in `async_send'
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.3/lib/async/io/generic.rb:62 in `block in wrap_blocking_method'
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.3/lib/async/io/generic.rb:156 in `write'
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.3/lib/async/io/stream.rb:258 in `block in drain_write_buffer'
               |     ~/.gem/ruby/2.7.0/gems/async-1.24.2/lib/async/semaphore.rb:80 in `acquire'
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.3/lib/async/io/stream.rb:247 in `drain_write_buffer'
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.3/lib/async/io/stream.rb:160 in `flush'
               |     ~/.gem/ruby/2.7.0/gems/protocol-http1-0.10.1/lib/protocol/http1/connection.rb:277 in `write_fixed_length_body'
               |     ~/.gem/ruby/2.7.0/gems/protocol-http1-0.10.1/lib/protocol/http1/connection.rb:332 in `write_body'
               |     ~/.gem/ruby/2.7.0/gems/async-http-0.50.2/lib/async/http/protocol/http1/server.rb:91 in `each'
               |     ~/.gem/ruby/2.7.0/gems/async-http-0.50.2/lib/async/http/server.rb:53 in `accept'
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.3/lib/async/io/server.rb:32 in `block in accept_each'
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.3/lib/async/io/socket.rb:73 in `block in accept'
               |     ~/.gem/ruby/2.7.0/gems/async-1.24.2/lib/async/task.rb:258 in `block in make_fiber'
```

**Comment by ioquatix** [comment]
Can you give me source code so I can repro?

**Comment by deepj** [comment]
Hm, I have troubles to reproduce it on a freshly generated Rails app. On the original app this is happening only more very random with the latest Falcon :(

**Comment by ioquatix** [comment]
It looks like hijack is not working correctly

**Comment by ioquatix** [comment]
Can you try the latest release.

**Comment by deepj** [comment]
@ioquatix tried, but no change :(

**Comment by deepj** [comment]
@ioquatix I've tried 0.36.3 for the last days and it seems the problem is gone. So I guess this can be closed

**Comment by ioquatix** [comment]
Do you have some time to peer on this?

**Comment by nare06** [comment]
<img width="792" alt="Screen Shot 2020-05-27 at 10 02 43 PM" src="https://user-images.githubusercontent.com/6347611/83047404-f7567180-a065-11ea-9379-4395218c55b5.png">
On falcon serve, I do find this issue. Not sure where the problem lies.
<img width="1112" alt="Screen Shot 2020-05-27 at 10 03 03 PM" src="https://user-images.githubusercontent.com/6347611/83047447-02110680-a066-11ea-848c-5559fb07c74b.png">

**Comment by ioquatix** [comment]
Thanks for the report, I will investigate.

**Comment by ioquatix** [comment]
I see the problem here: https://github.com/socketry/falcon/blame/45ca2be3cc8228e491b7b7298c228c2ba777ddc3/lib/falcon/adapters/rack.rb#L205

It's returning nil when there is a full hijack. At least, this seems somewhat wrong.

**Comment by ioquatix** [comment]
The error message is somewhat misleading since it only kills the request task and not the underlying connection, which should be working correctly. In any case, I'll introduce a dedicated exception for this case.

**Comment by ioquatix** [comment]
This should be fixed, however full hijack will present an exception in the log since it terminates the normal request flow control using an exception and I don't want to handle this case explicitly in async-http as I actually want to minimise the blast radius of the full hijack feature.
