### ISSUE TITLE
What's the max URI length

### ISSUE THREAD

**Issue by ekampp** [socketry/falcon#107]
Hey there. I'm evaluating different web servers for our Rails application because we're running into max URI size errors with the current implementation. 

Is there a max limit to the URI length that Falcon can process? If yes, is that configurable in case very long URIs are expected? 

PS. If this is not appropriate here, I'm happy to move it to a support forum somewhere, but I couldn't find one mentioned in the readme. 

Thanks in advance.

**Comment by ioquatix** [comment]
There is no maximum URL length except as limited by the underlying protocols.

That being said, I am planning to add some additional protections to HTTP/1 including a maximum pre-amble (request line and headers) data size.

**Comment by ioquatix** [comment]
Let me know if you have any other questions.
