### ISSUE TITLE
Support Project

### ISSUE THREAD

**Issue by fastengineer** [socketry/falcon#110]
I watch socketry libraries. It is really good. I want to support if you open a page on crowdfunding page. Example: https://opencollective.com/opensource

Thank you.

**Comment by ioquatix** [comment]
We have GitHub sponsorship, is that sufficient?

**Comment by fastengineer** [comment]
I didn't see it. Are you getting enough support?

**Comment by ioquatix** [comment]
The more support this project gets the more we can achieve, since I can focus more time on it. So the short answer is, we can always use more sponsorship.

**Comment by ioquatix** [comment]
@fastengineer Here is the latest progress report FYI.

https://www.codeotaku.com/journal/2020-04/open-source-progress-report/index

If you have budget for sponsorship, I am happy to discuss including your logo/link on those reports.

You can also provide sponsorship/support using the tiers on this page: https://github.com/sponsors/ioquatix

Let me know if there is anything else I can help with.
