### ISSUE TITLE
Add option to suppress "Server" header

### ISSUE THREAD

**Issue by gottlike** [socketry/falcon#112]
In a recent commit you (re-)added a mandatory `Server` header: https://github.com/socketry/falcon/commit/59bf99bc2d593d35d09bdd39b8019eeac780c55f

I get that it's in the spec, but https://www.ietf.org/rfc/rfc2068.txt strongly recommends to make it a configurable field. Also see https://www.troyhunt.com/shhh-dont-let-your-response-headers/ for a more detailed background on why this is a good idea.

**Comment by ioquatix** [comment]
I agree with you.

I'm considering models for building financial support for continued falcon development.

I looked at nginx, and the standard option requires commercial support:

http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens

I wonder if I should follow that model.

What do you think?

**Comment by gottlike** [comment]
The commercial version of nginx has an **additional** option of setting the value to a user defined string. But I wonder why anyone would consider this a valuable feature, since you can easily set or remove headers with the `add_headers` directive.

That said, I totally sympathize with "commercial open source" models in general! In my opinion commercial support in the sense of actual email/ssh + setup support makes the most sense. On top of that there could be additional features that make the user's life easier/more comfortable. In order to find out what kind of features this could be, you'd have to interview some enterprise users and talk to them about their biggest pain points with using/setting up falcon - imo.

However, security related topics/features should never be "commercial only".. that leaves a very bad taste and is kind of a "dark pattern", in my eyes.

**Comment by ioquatix** [comment]
Yeah, agree. I don't have time tonight but I will figure out some way to make it optional.

**Comment by ioquatix** [comment]
I decided to remove `date` and `server` header for network performance reasons.
