### ISSUE TITLE
Executable "console" conflicts with ...

### ISSUE THREAD

**Issue by brodock** [socketry/falcon#113]
When I was trying to gem install `falcon`, I got an error from this gem as it's a dependency that said:

```
process-metrics's executable "console" conflicts with omniauth-oauth2-generic
Overwrite the executable? [yN]
```

probably omniauth shouldn't be adding executables with such a generic name, but I think this is valid for this gem as well.

after looking at the sourcecode, I don't see it other than "console" being a dependency. Do you have any idea what's going on?

**Comment by ioquatix** [comment]
This should be fixed.
