### ISSUE TITLE
Rack::Lint::LintError occurs when Host: has no port number

### ISSUE THREAD

**Issue by shugo** [socketry/falcon#118]
falcon sets `env["SERVER_PORT"]` to an empty string if the Host: header field has no port number,
and Rack::Lint reports the following error when `env["SERVER_PORT"]` is an empty string.

```
Rack::Lint::LintError: env[SERVER_PORT] is not an Integer
```

Rack::Lint reports no error if env["SERVER_PORT"] is nil.

```
      assert("env[SERVER_PORT] is not an Integer") do
        server_port = env["SERVER_PORT"]
        server_port.nil? || (Integer(server_port) rescue false)
      end
```

How about not to set SERVER_PORT if Host: has no port number, or to set the default port number like puma?

https://github.com/puma/puma/blob/4.3.3/lib/puma/server.rb#L607

**Comment by ioquatix** [comment]
https://github.com/rack/rack/issues/1571

**Comment by ioquatix** [comment]
https://github.com/socketry/falcon/blob/1bea57d68588d1c9c0247d12fd5e216f3dc18eb8/lib/falcon/adapters/rack.rb#L179

We probably just need to change this.
