### ISSUE TITLE
falcon hosting on heroku  using falcon.rb

### ISSUE THREAD

**Issue by semdinsp** [socketry/falcon#121]
I was a bit confused by the documentation so i wondered if you could bless the following.  The confusion is production should only use the host command (and not serve) but there is no clear falcon.rb file. I have attached a sample file that works below.

a) deployment should be using falcon host  (and NOT falcon serve.  I have used serve successfully for about a year but thought i should be be upto date).
So my heroku Procfile now looks like:
```ruby
web: bundle exec falcon host 
# old was  web: bundle exec falcon serve -b http://0.0.0.0:${PORT:-3000} --count 3
```

my falcon.rb file in app directory looks like  

```ruby
#!/usr/bin/env -S falcon host
# frozen_string_literal: true
module Async::Container
  def self.processor_count
    ENV.fetch('FALCON_WORKERS') { Etc.nprocessors }
  rescue
    2
  end
end
puts "falcon processor count #{Async::Container.processor_count} cores: #{Etc.nprocessors} set FALCON_WORKERS env to override"
# Above courtesy of Daniel Evans
load :rack, :lets_encrypt_tls, :supervisor
myport=3000
myport=ENV['PORT'] if !ENV['PORT'].nil? and ENV['PORT']!=""
#puts "port set to [#{myport}] #{ENV.inspect}"
puts "port set to [#{myport}]"
hostname = File.basename(__dir__)
rack hostname, :lets_encrypt_tls do
  cache true
  # endpoint Async::HTTP::Endpoint.parse("http://localhost:#{myport}").with(protocol: 
  Async::HTTP::Protocol::HTTP2)
      endpoint Async::HTTP::Endpoint.parse("http://0.0.0.0:#{myport}").with(protocol: 
  Async::HTTP::Protocol::HTTP11)
  end
supervisor
```

ABOVE SEEMS TO WORK.  Can you bless it?  Your software has been plug and play for me with the exception of async-postgres

Question - how can I limit the servers spun up usng the host command (old count command in serve) as I was running out of memory in another heroku deployment and changing count to 2 fixed it.
[this pull request fixes this](https://github.com/socketry/falcon/pull/120)

thank you.

**Comment by ioquatix** [comment]
I will check this tomorrow.

**Comment by ioquatix** [comment]
Sorry, I lost track of this issue. I'll take a look at my earliest convenience.

**Comment by ioquatix** [comment]
Firstly, we provided `ASYNC_CONTAINER_PROCESSOR_COUNT` to override the default processor count.

The rest looks fine but it could be a bit tidier. I'll try to make some canonical example of how to do it.

**Comment by danmayer** [comment]
Also, looking try out Falcon on Heroku so a good example config would be great

**Comment by semdinsp** [comment]
here is sample which is i production for over a year.
any questions let me know.
It may not be updated with most recent versio so your mileage may vary...

**Comment by semdinsp** [comment]
sorry attachinng procfile as well..

here is sample which is i production for over a year.
any questions let me know.
It may not be updated with most recent versio so your mileage may vary...

**Comment by danmayer** [comment]
awesome thanks @semdinsp wow on fast response, I think the attachments aren't working or at least I can't see them on the github issue comments

**Comment by semdinsp** [comment]
they are short so have sent as embedded   —falcon.rb does NOT take advantage of latest env variables.  this is currently runnning well on heroku for multiple apps/code bases

procfile
web: bundle exec falcon host 

falcon.rb
#!/usr/bin/env -S falcon host
# frozen_string_literal: true

module Async::Container
  def self.processor_count
    # was: ENV.fetch('FALCON_WORKERS') { Etc.nprocessors }
    ENV.fetch('FALCON_WORKERS') { 2 }
  rescue
    2
  end
end

puts "falcon processor count #{Async::Container.processor_count} cores: #{Etc.nprocessors} set FALCON_WORKERS env to override"


load :rack, :lets_encrypt_tls, :supervisor
myport=3000
myport=ENV['PORT'] if !ENV['PORT'].nil? and ENV['PORT']!=""
#puts "port set to [#{myport}] #{ENV.inspect}"
puts "port set to [#{myport}]"
hostname = File.basename(__dir__)
rack hostname, :lets_encrypt_tls do
        cache true
 # endpoint Async::HTTP::Endpoint.parse("http://localhost:#{myport}").with(protocol: Async::HTTP::Protocol::HTTP2)
  
  endpoint Async::HTTP::Endpoint.parse("http://0.0.0.0:#{myport}").with(protocol: Async::HTTP::Protocol::HTTP11)
end

supervisor

**Comment by danmayer** [comment]
Thanks, this is really helpful

**Comment by ioquatix** [comment]
You can use `ASYNC_CONTAINER_PROCESSOR_COUNT` instead of `FALCON_WORKERS` monkey patch.

**Comment by trevorturk** [comment]
Thank you for this! I'd be curious to hear more details about this config, as I'm not sure what the various parts are doing. For example, what is the `lets_encrypt_tls ` bit doing? I thought I might be able to omit it since I'm using Heroku's SSL, but it appears to be necessary. Here's the config from above but with formatting for future readers:

ENV:
```
ASYNC_CONTAINER_PROCESSOR_COUNT=8
```

Procfile:
```
web: bundle exec falcon host
```

falcon.rb:
```ruby
#!/usr/bin/env -S falcon host
# frozen_string_literal: true

load :rack, :lets_encrypt_tls, :supervisor

hostname = File.basename(__dir__)
port = ENV["PORT"] || 3000
rack hostname, :lets_encrypt_tls do
  cache true
  endpoint Async::HTTP::Endpoint.parse("http://0.0.0.0:#{port}").with(protocol: Async::HTTP::Protocol::HTTP11)
end

supervisor
```

...but even then I'm not sure why we pick this `protocol` specifically -- is that the only one Heroku supports? Any additional info would be much appreciated, but thank you in any case for the pointers already!

**Comment by semdinsp** [comment]
sorry I just grabbed the code to get it to work.  I did not look into that line load: rack but it is an interesting question.  I will look into it a bit.

As a side note, I fiddled with the Async protocols as I wanted to run HTTP2 (quic?) but then i found out that heroku was not supporting http2.  Howevef if you don’t use heroku setting the protocol to HTTP2 works in this configuration and seems to be robust (at least on my testing).

**Comment by ioquatix** [comment]
```
ASYNC_CONTAINER_PROCESSOR_COUNT=8
```

Strickly speaking you should not need this, it will automatically scale depending on the number of CPU cores.

**Comment by trevorturk** [comment]
Ah, I was thinking this is how to control memory use... is there another way? (Generally, Rails apps seem to be memory constrained on Heroku in my experience.)

**Comment by semdinsp** [comment]
> (Generally, Rails apps seem to be memory constrained on Heroku in my experience.)
> 

I totally agree with this comment.  In my experience I need to tune down the number of threads to limit memory use on heroku for the $7 dyno class and in general for any size dyno.

I think it is interesting and a bit non intuitive that we use cpu count as a way to control memory usage.  Obviously we don’t need to change the name of the variable I just wanted to write a post so if newbies were having a problem with memory on heroku with rails they might see this comment.

**Comment by trevorturk** [comment]
Yes, I'm planning to work with @ioquatix on this a bit more and we hope to provide some docs to help explain the trade offs etc. I just wanted to post what I had so far on this thread since it'll likely be a few weeks before I can get back into this. 

I'm sure lots of people will be like me, starting from their experience with Puma, so I'd imagine people will be looking for guidance on how to port things over to Falcon, and how to optimize for Heroku etc.

**Comment by sebyx07** [comment]
@ioquatix what should be the pool of database? for puma you would do smth like:

```ruby
  on_worker_boot do
    config = ActiveRecord::Base.configurations[rails_env]
    config["pool"] = puma_max_threads
    ActiveRecord::Base.establish_connection
  end
```

and puma_max_threads usually is 5

**Comment by troex** [comment]
@sebyx07 recently came around some task - how to do something once worker is forked, so for my case it was to add next line into `config.ru`
```
require_relative 'after_fork'
```

I use preload script as well which simply loads all the app (sinatra in my case) that loading initiates connections which I want to close and connect again in the fork, take a look at https://github.com/rubyapi/rubyapi they have preload which loads rails application before it starts rack, so anything added to config.ru should be equivalent to `on_worker_boot`
