### ISSUE TITLE
Can non-async endpoint impact overall performance

### ISSUE THREAD

**Issue by tleish** [socketry/falcon#122]
I'm sure you are aware of this article which pitches puma over falcon.  

[Birds of a Fiber: A look at Falcon, a modern asynchronous web server for Ruby | Scout APM Blog](https://scoutapm.com/blog/birds-of-a-fiber)

Are their claims towards the end of the article correct?  If a non-async library is used from a single endpoint, can it also affect the overall performance of Falcon and other async endpoints?  In other words, if I have 5 endpoints, and one of them uses a non-async library.  This 1 endpoint can affect the performance of the other 4 endpoints?

I'm currently using the [carrierwave](https://github.com/carrierwaveuploader/carrierwave) and [carrierwave-aws](https://github.com/sorentwo/carrierwave-aws) gems with falcon to save files to AWS.  I'm pretty sure it does not use an async library to communicate with AWS.

**Comment by ioquatix** [comment]
Yes I wrote a response to that article but they've deleted all the comments from that blog which is unfortunate.

The short answer is yes but the longer answer is more complex.

## Per-Thread Fiber Scheduler

With Ruby 3, many of these situations will be covered provided the libraries use Ruby I/O instances.  You can check some of the details on this blog post which has links to some examples and a youtube live stream about the changes: https://www.codeotaku.com/journal/2020-06/open-source-progress-report/index

## The Nature of Blocking Operations

At a more fundamental level, all servers will experience some blocking. The nature of that blocking is different between a server like Falcon and Puma and the impact on latency. Let me give you an example:

- Puma: 8 workers each with 16 threads.
- Falcon: 8 processes each with 16 event loops.

In this configuration, given a blocking I/O, Puma can handle 8*16 simultaneous requests. Falcon is the same. However, Puma cannot handle **more** than 8*16 simultaneous requests, but Falcon potentially **can** if you use non-blocking primitives.

If you want to do a 1-1 comparison of Falcon vs Puma latency, you must ensure they have the same resources allocated. That being said, there is a different way to organise this:

- Puma: 8 workers each with 16 threads.
- Falcon: 4 processes each with 1 event loop.

In this case, even head to head, I've seen Falcon outperform Puma, and scale better when non-blocking I/O is a significant part of the latency.

**Comment by tleish** [comment]
@ioquatix -  This was very helpful.  I really appreciate you taking the time with a detailed answer and all your work on the falcon/async libraries.

**Comment by ioquatix** [comment]
You are most welcome!

**Comment by FranklinYu** [comment]
@tleish If you are concerned about the performance when uploading large files to AWS, consider [using presigned URL](https://docs.aws.amazon.com/AmazonS3/latest/dev/UploadObjectPreSignedURLRubySDK.html) to allow your client (browser) to upload the files themselves?
