### ISSUE TITLE
rack1 gemfile fails in tests

### ISSUE THREAD

**Issue by olleolleolle** [socketry/falcon#125]
https://github.com/socketry/falcon/pull/124/checks?check_run_id=906495785

> 
> Bundler could not find compatible versions for gem "rack":
>   In rack1.gemfile:
>     rack (~> 1.0)
> 
>     utopia-project was resolved to 0.13.3, which depends on
>       utopia (~> 2.14) was resolved to 2.18.0, which depends on
>         rack (~> 2.2)

**Comment by ioquatix** [comment]
Yes.

It looks like optional groups still fail even if not actually used.

- https://github.com/rubygems/rubygems/issues/3730
- https://github.com/rubygems/rubygems/issues/3837

Not sure what the solution is here. `bundler` tries to resolve it regardless of whether it's being used or not.

**Comment by olleolleolle** [comment]
Super!
