### ISSUE TITLE
Thread-safety with falcon and sinatra

### ISSUE THREAD

**Issue by onli** [socketry/falcon#15]
Hi. That's just a question, hope that's okay.

The Readme is saying that in Rails before 5.x, there will be limited performance and deadlocks because of the needed `Lock`-module. What's the compatibility situation with Sinatra (and other frameworks)? Will it also be necessary to specify something like `config.threadsafe!`?

**Comment by ioquatix** [comment]
That's a good question.

It is a bad idea to use anything like `Rack::Lock`. I hope other frameworks don't use it. It will depend on the specific framework to be thread-safe and re-entrant safe.
