### ISSUE TITLE
Falcon running out of file descriptors

### ISSUE THREAD

**Issue by ThibG** [socketry/falcon#17]
In my quest of having Mastodon handle requests asynchronously, I have toyed with using Falcon instead of Puma, and making HTTP.rb use wrappers provided by `async-io`.
This seems to work reasonably well except the falcon processes eventually crash because it ran out of file descriptors. This may due to HTTP.rb leaking sockets, as hinted by https://github.com/socketry/async-io/pull/13, but stopping the process because it couldn't accept one connection doesn't seem right.

```
Traceback (most recent call last):
	7: from /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/async-1.10.3/lib/async/task.rb:74:in `block in initialize'
	6: from /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/async-io-1.15.5/lib/async/io/shared_endpoint.rb:74:in `block (2 levels) in bind'
	5: from /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/async-io-1.15.5/lib/async/io/shared_endpoint.rb:102:in `block in accept'
	4: from /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/async-io-1.15.5/lib/async/io/socket.rb:61:in `accept_each'
	3: from /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/async-io-1.15.5/lib/async/io/socket.rb:86:in `accept'
	2: from /home/mastodon/live/vendor/bundle/ruby/2.5.0/gems/async-io-1.15.5/lib/async/io/generic.rb:128:in `async_send'
	1: from /usr/lib/ruby/2.5.0/socket.rb:593:in `accept_nonblock'
/usr/lib/ruby/2.5.0/socket.rb:593:in `__accept_nonblock': Too many open files - accept(2) (Errno::EMFILE)
```

**Comment by ioquatix** [comment]
That seems like a reasonable request. I will take a look.

**Comment by ioquatix** [comment]
Okay, so I'm just wondering, what is the correct behaviour?

If the process crash, should we restart it?

Should we detect file descriptor exhaustion and try to do something?

**Comment by ioquatix** [comment]
If a child process crashes, it will be restarted. That is the default now. So at least in the case of badly behaving code, this should be less of an issue. Also, use `Async::HTTP::Internet` as a replacement for `http.rb`. It's going to scale way better.
