### ISSUE TITLE
Feature request: rename thread/processes names

### ISSUE THREAD

**Issue by rhaamo** [socketry/falcon#18]
It would be great to have the threads and/or processes renamed with something like puma does :

```
root@xxx:/etc/telegraf# ps faux | grep puma
root     12595  0.0  0.0  13084  1024 pts/4    S+   Sep29   0:00  |                       \_ grep puma
mastodo+ 23771  0.0  0.6 518752 106464 ?       Ssl  Sep20   0:44 puma 3.11.4 (tcp://0.0.0.0:3100) [live]
mastodo+ 23968  0.0  1.8 1173088 314728 ?      Sl   Sep20   7:11  \_ puma: cluster worker 0: 23771 [live]
mastodo+ 23983  0.0  1.4 857144 238300 ?       Sl   Sep20   6:49  \_ puma: cluster worker 1: 23771 [live]
```

Having that kind of thing with falcon would help monitoring/graphing individual processes.

**Comment by ioquatix** [comment]
I've implemented basic support for this in Falcon v0.19.1 - it's not really good yet - it turns out on macOS `setproctitle` doesn't work very well. In any case, the basic issue here is implemented and I hope over time I can improve it.
