### ISSUE TITLE
Avoid using require_relative for bin/falcon

### ISSUE THREAD

**Issue by rubyFeedback** [socketry/falcon#187]
Invocation example:

    falcon serve --port 3000

Error response (split onto two lines, to make it easier to read on github here):

    /usr/bin/falcon:23:in `require_relative': cannot load such file --
    /home/Programs/Ruby/3.1.2/lib/falcon/command (LoadError)         from /usr/bin/falcon:23:in `<main>' 

Background explanation: my ruby is kept in /home/Programs/Ruby/VERSION/ such as VERSION being 3.1.2/.

Due to this I tend to not have bin/ of gems in the directory at ~/.gem/somewhere. So after I installed falcon via
"gem install falcon", I did not know where the binary was. Traditional FHS assumes /usr/ and /usr/bin/ as well
as /usr/lib/.

So I downloaded the .gem, extracted it, then did invoke oldschool setup.rb to install it. Then I would symlink from
/usr/bin/falcon to the falcon at  /home/Programs/Ruby/3.1.2/bin/falcon.

require_relative makes assumption about the file path that are probably correct in most cases, but in my case
it leads to breakage. Using just "require" as such suffices - no idea why require_relative is used here.

If you can, could you change the require_relative() calls to require() instead? It should work just fine, I
use it on my own gems and don't have that issue. You can reason that most ruby users use a setup
where this line is ok:

    require_relative '../lib/falcon/command'

And you would most likely be correct. But when I use it as a symlink then this require_relative makes
an incorrect assumption, whereas for whatever the reason, a simple require() instead avoids these
problems, e. g.

    require 'falcon/command' # I think this variant should work, but perhaps your use
                             # case requires you to use require_relative, I can't say

**Comment by ioquatix** [comment]
I understand your problem, however I prefer to use `require_relative` simply to ensure the files are loaded from the right source location. I think rather than using a symlink, it can be better to create a stub loader, which is what RubyGems actually does.
