### ISSUE TITLE
Only the first `Set-cookie` seem to get through

### ISSUE THREAD

**Issue by ThibG** [socketry/falcon#19]
I am not sure exactly why, but it seems like when there are multiple `Set-Cookie` headers, only the first one gets through to the client.

**Comment by ioquatix** [comment]
Okay this should be fixed, could you test and let me know?

**Comment by ThibG** [comment]
It seems to work, thanks!

**Comment by ioquatix** [comment]
I just found another issue, with HTTP/2 which I need to fix, hold tight there is going to be another release shortly.
