### ISSUE TITLE
Rails thread safety issues

### ISSUE THREAD

**Issue by ioquatix** [socketry/falcon#20]
The documentation regarding thread safety isn't sufficient and this sometimes causes Rails apps to deadlock.

**Comment by ioquatix** [comment]
@Stex can you please check https://github.com/socketry/falcon#thread-safety-rails--5x as I don't think your report is the same as this issue.

**Comment by Stex** [comment]
@ioquatix As far as I see it, `threadsafe!` is [no longer available](https://apidock.com/rails/Rails/Application/Configuration/threadsafe%21) in Rails 4.2, so I thought it wouldn't be necessary.

If I'm not completely blind, maybe the README should be updated regarding this.

**Comment by ioquatix** [comment]
In any case, I will update the README to reflect this, but can you let me know what's going on, on your end?

**Comment by rjocoleman** [comment]
@ioquatix 

Regarding the deadlock in Rails 4.2 (I agree this is different from the issue you opened) - I ran up against this today on a Rails 4.2.10 application - it looks like the code in Rails 4.2 that adds the middleware is a little different than you linked:

https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/application/configuration.rb#L25 (default `nil`)

https://github.com/rails/rails/blob/4-2-stable/railties/lib/rails/application/default_middleware_stack.rb#L29

So Rails 4.2 need to specify an explicit `config.allow_concurrency = false` 
`config.threadsafe!` isn't present and trying to set that will error.

**Comment by ioquatix** [comment]
@rjocoleman So, what you are saying, is that in order for Rails 4.2 to break, you must have an explicit `config.allow_concurrency = false`?

**Comment by rjocoleman** [comment]
Yikes, sorry I was struggling to send that message due to the Github downtime and it got a little garbled in my attempts.

Just the opposite, rails 4.2 will break by default because the default in that version is essentially `config.allow_concurrency = false` (it's nil).

Rails 4.2 users need to explicitly set `config.allow_concurrency = true`.

**Comment by ioquatix** [comment]
I was under the impression that `nil` meant "default". i.e. it should allow concurrency.

`nil == false` is not true.

I'd like to know for sure exactly what is going on.

**Comment by rjocoleman** [comment]
In this version of Ruby (`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]), in a Pry Rails console (4.2.10)

```ruby
[1] pry(main)> puts 'foo' unless nil
foo
=> nil
[2] pry(main)> puts 'foo' unless false
foo
=> nil
[3] pry(main)> puts 'foo' unless true
=> nil
```

`middleware.use ::Rack::Lock unless allow_concurrency?` is the line in this version.

**Comment by ioquatix** [comment]
@rjocoleman can you check the proposed changes to the documentation and let me know if you think it's clear enough (and correct!)?

**Comment by rjocoleman** [comment]
@ioquatix looks great to me, thanks!

**Comment by ioquatix** [comment]
Okay, I have updated documentation. If you have any additional things to add to that, any problems or things you could help others, please don't hesitate to add a PR updating the documentation. Thanks so much for your patience and feedback.
