### ISSUE TITLE
warning: 'Rack::Handler is deprecated and replaced by Rackup::Handler' on Rack 3

### ISSUE THREAD

**Issue by fmqa** [socketry/falcon#200]
### Environment

* falcon-0.42.3
* rack-3.0.4.1
* rackup-2.0.0

### Steps to reproduce

Start any application e.g. [examples/hello](https://github.com/socketry/falcon/blob/v0.42.3/examples/hello/config.ru) using `rackup -s falcon`. The following warning will appear on the console:

> Rack::Handler is deprecated and replaced by Rackup::Handler

### Expected result

Applications can be started without any warnings.

### Hint/Suggestion to Fix the Issue

https://github.com/socketry/falcon/blob/15d7e836c7c736fd30bf21d214711d5d26c1971a/lib/rack/handler/falcon.rb#L3 could be changed to 

```ruby
begin
  require 'rackup/handler'
rescue LoadError
  require 'rack/handler'
end
```

Or some other conditional loading mechanism could be used.

**Comment by ioquatix** [comment]
Yeah, I'm working to fix this, but it's not quite done yet.
