### ISSUE TITLE
Concurrent Database Transaction worries

### ISSUE THREAD

**Issue by buhrmi** [socketry/falcon#214]
Hi there,

I've been testing Falcon since a few days and am pretty much in awe what has been accomplished here.

However, I've stumbled upon [this](https://news.ycombinator.com/item?id=27238671) comment on Hackernews regarding the per-thread nature of the pg gem and the issues with concurrent transactions.

So basically, my question is if this has already been addressed in some way or is this still an issue? What would we need to do to fix this? Write a new adapter using the `db-postgres` gem? Been looking at the examples in the readme and it doesn't mention concurrent transaction, only concurrent queries. So right now I'm hoping I can get a bit of advice how to proceed. Would it be wise to switch back to puma while concurrent transactions are still being worked on?

**Comment by ioquatix** [comment]
Use the latest version of Rails with per-fiber concurrency.

https://blog.saeloun.com/2022/02/23/rails-fiber-safe-connection-pools/

**Comment by buhrmi** [comment]
Oh wow, you guys rock so much
