### ISSUE TITLE
Should the 'virtual' command be changing the Console.logger log level?

### ISSUE THREAD

**Issue by jakeonfire** [socketry/falcon#222]
https://github.com/socketry/falcon/blob/4002aea74988a9b6f5560363eb7738084308152d/lib/falcon/command/virtual.rb#L63

`debug` is way too noisy in production. (is there a good way to override the Console.logger log level in a rails app?)

**Comment by jakeonfire** [comment]
adding
```ruby
Console.logger.level = Console::Logger::LEVELS[:warn]
```
to `falcon.rb` works for now. i still don't think it should default to `debug`, however.

**Comment by ioquatix** [comment]
Yeah, that's a fair point, not sure what I was thinking at the time - I'll reconsider it.

**Comment by jakeonfire** [comment]
even changing that line to `ENV['CONSOLE_LEVEL'] ||= 'debug'` would make it easier to override imo if you have a reason for a default.

**Comment by ioquatix** [comment]
This is fixed and will be released in the next version bump.
