### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by thbar** [socketry/falcon#229]
Hi!

I was looking into installing Falcon for some reverse-proxy testing.

The repo led me to https://socketry.github.io/falcon/guides/getting-started/index.html, which just mentions to "run" the `falcon` command, but not how to install it.

I could definitely dive into the code but I would like to leverage my experience to improve the documentation :-) 

A newcomer might wonder if that's something you just "put" in your `Gemfile` in the `development` group, or `brew install` or similar etc.

Thank you for your feedback, and hope it will help other newcomers!

**Comment by ioquatix** [comment]
Ah right you are, I'll update the documentation, thanks for calling it out.

To install it, simply run `gem install falcon` and in addition if you have an app, you can do `bundle add falcon` to add it to your gem file.

**Comment by ioquatix** [comment]
I've done a first pass over the getting started guide: https://socketry.github.io/falcon/guides/getting-started/index#installation

**Comment by ioquatix** [comment]
Let me know if you think there are further updates that can be made to the getting started guide, or feel free to open a PR :)

**Comment by thbar** [comment]
@ioquatix this makes perfect sense, thank you!
