### ISSUE TITLE
The default https://localhost:9292 bind doesn't work on my machine

### ISSUE THREAD

**Issue by janko-m** [socketry/falcon#35]
The by default Falcon binds on `https://localhost:9292`, and that doesn't work on my machine because it doesn't support SSL. This is using the simplest `config.ru`:

```rb
# config.ru
run -> (env) { [200, {}, []] }
```
```
$ falcon serve
I, [2018-11-10T18:07:25.960900 #82757]  INFO -- : Falcon taking flight! Binding to #<Falcon::Endpoint https://localhost:9292/ {}> [Async::Container::Forked with concurrency: 4]
I, [2018-11-10T18:07:25.965411 #82786]  INFO -- : Send `kill -USR1 82786` for detailed status :)
I, [2018-11-10T18:07:25.965867 #82787]  INFO -- : Send `kill -USR1 82787` for detailed status :)
I, [2018-11-10T18:07:25.966193 #82788]  INFO -- : Send `kill -USR1 82788` for detailed status :)
I, [2018-11-10T18:07:25.966607 #82789]  INFO -- : Send `kill -USR1 82789` for detailed status :)
E, [2018-11-10T18:07:29.155505 #82786] ERROR -- #<Async::IO::SSLServer:0x00007fb4ac1c2a10>: SSL_accept returned=1 errno=0 state=SSLv2/v3 read client hello A: http request (OpenSSL::SSL::SSLError)
/Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `accept_nonblock'
/Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:128:in `async_send'
/Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.16.4/lib/async/io/generic.rb:47:in `block in wrap_blocking_method'
/Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-io-1.16.4/lib/async/io/ssl_socket.rb:126:in `block in accept'
/Users/janko/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/async-1.10.3/lib/async/task.rb:74:in `block in initialize'
```
```
$ curl localhost:9292
curl: (56) Recv failure: Connection reset by peer
```

My environment:

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]

$ ruby -r openssl -e 'puts OpenSSL::VERSION, OpenSSL::OPENSSL_VERSION, OpenSSL::OPENSSL_LIBRARY_VERSION'
2.1.0
OpenSSL 1.0.2o  27 Mar 2018
OpenSSL 1.0.2p  14 Aug 2018

$ falcon -v
falcon v0.19.3

$ uname -a
Darwin Jankos-MacBook-Pro-2.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
```

**Comment by ioquatix** [comment]
Don't you need to tell curl to use https, e.g. `curl https://localhost:9292`?

**Comment by janko-m** [comment]
You're right. Now I get a different error:

```
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
```

But that's just because I don't understand SSL certificates yet, so I probably need to configure something.

Visiting `https://localhost:9292/` in the browser doesn't work either (Chrome), as I get asked to select a certificate I don't have, and when I refuse I get a `NET::ERR_CERT_AUTHORITY_INVALID`. I've been glancing a little at https://letsencrypt.org/docs/certificates-for-localhost/, but for that it seems I have to choose the generated certificate when starting the `falcon server`. Do you think you could help me out here?

**Comment by ioquatix** [comment]
If you just want it to work use `--insecure` or try setting `--cacert ~/.localhost/localhost.key` might work.

The certificate is generated automatically by https://github.com/socketry/localhost

You should follow these instructions: https://github.com/socketry/localhost#chrome

**Comment by ioquatix** [comment]
This is certainly an area which I don't think has been explored very much - self-signed localhost certificates. I certainly think there is room for improvement on the browser, but it might also be possible to use letsencrypt. Localhost certificates by their nature (everyone uses `localhost` as the CN) can never be fully secure.

Additionally, I've noticed that when clients terminate connections, they sometimes simply drop the connection without closing it gracefully. While this doesn't seem to be what you have above, there are certainly similar error messages w.r.t SSL and abruptly terminated TCP sessions.

I'd like to dig into this a bit more because I think we should solve these problems or at the very least, capture and ignore the exceptions if they are harmless.
