### ISSUE TITLE
Reasons for deleting Content-Length always?

### ISSUE THREAD

**Issue by julik** [socketry/falcon#41]
I was wondering why Falcon was making the assumption that the Content-Length that is provded by the application is by definition incorrect? I do in fact have multiple applications where it is correct, and I don't need either chunked transfer encoding to be applied or the content length to be applied anew. Rack has a mechanism for it that if Content-Length is provided the ContentLength middleware is bypassed. Or (IMO) there should be a way to indicate to the server "Yes, I have a streaming response but it is not going to be endless, neither do I want chunked encoding to be applied on top".

There was a similar conundrum with https://github.com/puma/puma/pull/711 (an incorrect assumption that if you are using hijack you will be doing a long response of arbitrary length) which has been resolved. There are usability concerns here of course but just silently `delete()`ing useful data the upstream app explicitly and deliberately sets is IMO not a nice thing to do.

**Comment by ioquatix** [comment]
Firstly, I believe you are wrong about your assumptions. This isn't about what is nice or not but what is necessary to ensure consistent behaviour between `HTTP/1` and `HTTP/2`.

Rack response is considered in the context of `HTTP/1.1`. The server is actually functioning as a proxy between the client and the application.

The `Content-Length` is used to indicate the length of the response body is known ahead of time. This header is deleted from the headers and set into the output body. If the protocol allows for it, the `content-length` will be set in the response to the client.

Here is where it is deleted:

https://github.com/socketry/falcon/blob/52507e7ba64d8473186f7b8b3ff304957438b82d/lib/falcon/adapters/output.rb#L32-L37

Here is where it is exposed:

https://github.com/socketry/falcon/blob/52507e7ba64d8473186f7b8b3ff304957438b82d/lib/falcon/adapters/output.rb#L61

And here is where we check if it has a content-length provided:

https://github.com/socketry/http-protocol/blob/0898542c320b0ef8af2c97137f0c4926db9750c1/lib/http/protocol/http1/connection.rb#L265-L266

And here is where the header is sent back to the client:

https://github.com/socketry/http-protocol/blob/0898542c320b0ef8af2c97137f0c4926db9750c1/lib/http/protocol/http1/connection.rb#L212

Provided you don't do anything between the output body and what is sent to the client, this header will pass through without any changes.

However, if you have something like compression or any other processing which affects the content-length, it might not be sent to client.

**Comment by ioquatix** [comment]
Also, I'm pretty sure falcon doesn't support partial hijack, so that's not relevant. If you do a full hijack, it's your responsibility to send headers or whatever :)

**Comment by julik** [comment]
Thank you for the explanations!

> Firstly, I believe you are wrong about your assumptions

That is entirely true, and I seriously love to be proven wrong. I also don't understand the "wrap HTTP1 in HTTP2" semantics completely at this stage. But let's try a smaller example.  Imagine I bind falcon in HTTP1 mode with the following command:

```
$ falcon serve --concurrency 1 --bind "http://localhost:9292" --config mini_falcon.ru
```

for ease of local testing and because I doubt my downstream proxies (CloudFront primarily)
support HTTP2. Then I make a response in my Rack app like this:

```ruby
# config.ru
run ->(env) {
  current_task = Async::Task.current
  async_output_body = Async::HTTP::Body::Writable.new
  string_of_known_size = "A very good day to you sir!"
  clen = string_of_known_size.bytesize * 2
  hh = {"Content-Length" => clen.to_s}

  current_task.reactor.async do |task|
    async_output_body.write(string_of_known_size)
    task.yield
    async_output_body.write(string_of_known_size)
  ensure
    async_output_body.close
  end

  [200, hh, async_output_body]
}

```

When I hit falcon with Curl I do not get the download progress since the header gets stripped. I also need to support the `Range:` header from the upstream client and handle it on my end, and reply with a valid `Content-Range:`. In HTTP1 I am supposed to also accompany it with `Content-Length` which contains the size of the range that is going to be sent. Now, you say that

> If the protocol allows for it, the content-length will be set in the response to the client.

but this is not what I am observing in my test with the aforementioned command (bind to http plain) and it is also to be expected since falcon doesn't know how large the body is going to be

```
julik@nanobuk ~ $ curl -v http://localhost:9292/ > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9292 (#0)
> GET / HTTP/1.1
> Host: localhost:9292
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200
< server: falcon/0.19.6
< date: Sun, 09 Dec 2018 13:46:31 GMT
< transfer-encoding: chunked
< 
{ [33 bytes data]
100    54    0    54    0     0   5110      0 --:--:-- --:--:-- --:--:--  5400
* Connection #0 to host localhost left intact
julik@nanobuk ~ $ 
```

So it seems that falcon both insists on switching to chunked encoding and removes content-length. `Async::HTTP::Body::Writable` does not have `length=` so I can't set it upfront. This does work however:

```
class NotInfiniteBody < Async::HTTP::Body::Writable
  def initialize(*any, length:)
    super(*any)
    @length = length
  end
end

run ->(env) {
  current_task = Async::Task.current
  string_of_known_size = "A very good day to you sir!"

  clen = string_of_known_size.bytesize * 2
  async_output_body = NotInfiniteBody.new(length: clen)

  hh = {"Content-Length" => clen.to_s}

  current_task.reactor.async do |task|
    async_output_body.write(string_of_known_size)
    task.yield
    async_output_body.write(string_of_known_size)
  ensure
    async_output_body.close
  end

  [200, hh, async_output_body]
}
```

yields

```
julik@nanobuk ~ $ curl -v http://localhost:9292/ > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9292 (#0)
> GET / HTTP/1.1
> Host: localhost:9292
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200
< server: falcon/0.19.6
< date: Sun, 09 Dec 2018 13:56:14 GMT
< content-length: 54
< 
{ [54 bytes data]
100    54  100    54    0     0   4813      0 --:--:-- --:--:-- --:--:--  4909
* Connection #0 to host localhost left intact
julik@nanobuk ~ $ 
```

Then chunking is disabled as well. Could work, but

* I feel a bit uneasy overriding a private instance variable on someone else's (library's) object
* If there is a Content-Length and it gets deleted in this situation - and if the chunking gets applied - I would appreciate a log message telling me what I should do instead

**Comment by ioquatix** [comment]
Thanks for all the details I will take a look when I have some time.

**Comment by ioquatix** [comment]
I believe this is what you need to use:

https://github.com/socketry/async-http/blob/14e8db8f022d677c47adbcb4079e90eb6aade8c6/lib/async/http/body/writable.rb#L33

**Comment by julik** [comment]
🤦‍♂️ 😍  thank you! Missed it in plain sight. Would be rad to have keyword arguments for these.

**Comment by ioquatix** [comment]
What benefit do you think you'd get from keyword arguments? It's an allocation/memory overhead.

**Comment by julik** [comment]
The benefit is that it would allow additional arguments for the constructor as the API evolves. The existing implementation is good as well and fits what I want to do ;-)

**Comment by ioquatix** [comment]
Okay I will take that into consideration. As it seems like your issue is resolved, I will close this issue.
