### ISSUE TITLE
falcon seems to require Rack ~> 2.0 despite what's in the gemspec

### ISSUE THREAD

**Issue by ainar-g** [socketry/falcon#45]
`lib/falcon/adapters/rack.rb` mentions `Rack::RACK_VERSION`, `Rack::RACK_INPUT` and many other constants that seem to have appeared in Rack 2.0. I was able to launch falcon by monkey-patching them on my Rails 4.2 project, but I'm not sure if it's the right solution. It seems like the gemspec needs to be updated.

**Comment by ioquatix** [comment]
Thanks for this report. Do you still need to use Rack 1.x?

**Comment by ainar-g** [comment]
Yes, Rails 4.2 [requires Rack ~> 1.6](https://github.com/rails/rails/blob/4-2-stable/actionpack/actionpack.gemspec). The monkey-patches seem to work OK, but I'd prefer to not monkey-patch at all.

**Comment by ioquatix** [comment]
Thanks for reporting this problem. This change was made in recent versions of `falcon`. I didn't know it was only `rack ~> 2.0` which had these constants. I'll probably just define the ones that I use in `falcon` itself. That being said, is there any reason why Rails 4.x can't use Rack 2.0?

**Comment by ainar-g** [comment]
I don't know. You should probably ask DHH about it :-) Probably no one wants to update Rails 4, seeing how they're already working on Rails 6.

**Comment by ainar-g** [comment]
Oh, and thank you for the fix!

**Comment by ioquatix** [comment]
I am going to make a new release shortly... will give you an update.

**Comment by ioquatix** [comment]
I've added a `rack ~> 1.0` build to the travis test matrix, so we should avoid any regressions like this in the future.

**Comment by ainar-g** [comment]
Can confirm, the fix works. Thanks again.
