### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by deepj** [socketry/falcon#48]
Hello,
it would be nice if a changelog has been available. It's not easy to read all commits, and some summary of changes is always better than this.

I like the puma changelog https://github.com/puma/puma/blob/master/History.md

Is it possible to have in the falcon repository?

**Comment by ioquatix** [comment]
It's a good idea. I considered the project to immature to require it, but now that's changing.

Is there some way to automatically generate a change log from commit information? Something like that would things things easier. Even just a tool which you could point at the git repo and it could build the change log.

**Comment by deepj** [comment]
I don't have a good experiences with automated change logs from commits. If there is a change log on projects on which I'm working I make them manually.

**Comment by ioquatix** [comment]
Do you think should be a separate file or part of the README?

**Comment by deepj** [comment]
I prefer a seperated file. README has a different purpose from my point of view.

**Comment by ioquatix** [comment]
I reached out on ruby.social and @jeromedalbert suggested https://keepachangelog.com as a guide.

**Comment by jeromedalbert** [comment]
> Is there some way to automatically generate a change log from commit information?

> Using commit log diffs as changelogs is a bad idea: they're full of noise. Things like merge commits, commits with obscure titles, documentation changes, etc.
> https://keepachangelog.com

This leads me to think that you might have to do it manually; but you could use git commits as a source of inspiration to speed writing it up significantly.

> Do you think should be a separate file or part of the README?

Yeah maybe put that in a `CHANGELOG.md` or `CHANGELOG` file as suggested by https://keepachangelog.com.

**Comment by TheSmartnik** [comment]
@ioquatix if it's still relevant, you can use [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator). I haven't used it myself, but seems like a great tool

**Comment by ioquatix** [comment]
We will introduce `changes.md` going forward. I may automate it, but for now it will just be by hand.
