### ISSUE TITLE
No async task available when streaming http input to container using docker-api

### ISSUE THREAD

**Issue by xsresearch** [socketry/falcon#52]
Passing the raw http input stream from falcon to a docker container stdin through the docker-api module is causing an error to be raised in the async library.

This error does not occur if puma is used, however in that case it buffers the raw input to a file so the code path may be different.

Pre-reading the stream when using falcon and wrapping in a StringIO also eliminates the error, but both of these workarounds cause the entire stream to be read into memory, which is what I am trying to avoid.

The following error is generated (framework being used in Sinatra):

```
Excon::Error::Socket: No async task available! (RuntimeError)
      |    /usr/local/bundle/gems/async-1.15.1/lib/async/task.rb:143 in 'current'
      |    /usr/local/bundle/gems/async-1.15.1/lib/async/wrapper.rb:98 in 'wait_readable'
      |    /usr/local/bundle/gems/async-io-1.18.2/lib/async/io/generic.rb:145 in 'async_send'
      |    /usr/local/bundle/gems/async-io-1.18.2/lib/async/io/generic.rb:47 in 'block in wrap_blocking_method'
      |    /usr/local/bundle/gems/async-io-1.18.2/lib/async/io/stream.rb:195 in 'fill_read_buffer'
      |    /usr/local/bundle/gems/async-io-1.18.2/lib/async/io/stream.rb:76 in 'read_partial'
      |    /usr/local/bundle/gems/async-http-0.38.0/lib/async/http/body/fixed.rb:50 in 'read'
      |    /usr/local/bundle/gems/falcon-0.24.0/lib/falcon/adapters/input.rb:122 in 'read_next'
      |    /usr/local/bundle/gems/falcon-0.24.0/lib/falcon/adapters/input.rb:73 in 'read'
      |    /usr/local/bundle/gems/docker-api-1.34.2/lib/docker/util.rb:68 in 'copy_stream'
      |    /usr/local/bundle/gems/docker-api-1.34.2/lib/docker/util.rb:68 in 'block (2 levels) in hijack_for'
```

Difficult to immediately say if the problem is being caused in docker-api, falcon, one of the async library components or in the specific implementation I am using.

Please feel free to provide suggestions as to how I can best diagnose the root cause.

**Comment by ioquatix** [comment]
The problem is here:

`      |    /usr/local/bundle/gems/docker-api-1.34.2/lib/docker/util.rb:68 in 'copy_stream'`

You are passing an IO wrapper into a non-async aware process.

You probably want to pass the underlying IO or run it in an async context. `Wrapper#io` or `Async do ... end` respectively.

**Comment by xsresearch** [comment]
@ioquatix Thanks very much, running the copy_stream call in Async fixed the issue. Ideally I would prefer the first method of passing in the underlying IO as this would prevent the need to patch the docker-api.

The stream is a Falcon::Adapters::Input. Is there a simple way of getting to the underlying IO? This seems to contain an Async::HTTP::Body, then an Async::IO::Socket which contains a socket IO, but passing this in causes a hang which I haven't got to the bottom of yet. Would appreciate any further suggestions.

**Comment by ioquatix** [comment]
There is no guarantee that the underlying "IO" is actually a raw socket. It might be SSL, it might be HTTP/2. The only general way to do this is to use `Async do ... end`. Even for HTTP/1, there are data framing issues. Trying to read from the raw socket in this instance is only going to cause pain.

**Comment by ioquatix** [comment]
`Async::IO::Socket` has `#io` which returns the underlying IO but trying to read from that is probably going to foobar the connection from that point forward. The only way this could work is if you hijack the connection, which does do the appropriate things with the socket. You'll need to make sure you handle HTTP/1 chunked encoding and also close the socket when you are done with it. This will also blow away persistent connections.

**Comment by xsresearch** [comment]
@ioquatix Thanks for the suggestions, much appreciated. I think I'll stick to Async for the meantime as the socket hijack sounds like more hassle than it is worth and more potential to go wrong.

Issue can be closed as not related to Falcon.
