### ISSUE TITLE
Daemonize and start/stop service

### ISSUE THREAD

**Issue by pelcasandra** [socketry/falcon#55]
So far, I'm only able to start the server with `falcon serve`.

Is there any way to daemonize it and point to a pidfile? And even better, is it possible to stop the server  somehow sending the pidfile or state file?

One of the things that I like of `puma` is that it can be easily configured with `monit` using `capistrano` to automatically start and stop. 

```
# Example of monit recipe for automatically start/stop puma
check process puma_app_production
  with pidfile "/var/www/app/shared/tmp/pids/puma.pid"
  # shorted for brevity
  start program = "bundle exec puma -C /var/www/app/shared/puma.rb --daemon'"
  stop program = "bundle exec pumactl -S /var/www/app/shared/tmp/pids/puma.state stop'"                                                                                                                                                                             
```

Since I added `tus` to the app, I'd like to implement something like this for `falcon` as well so I make sure the service is always on or if is not it starts itself. 

I can't see to find a reliable way to keep the process up otherwise. 

This seems to be like a basic requirement for production usage, so I may be well missing something out.

**Comment by ioquatix** [comment]
I've been playing around with these ideas recently.

My current method for deployment is to use something like `systemd` which can restart the process if it crashes.

Here is an example config file: https://github.com/socketry/falcon-benchmark/blob/master/setup/falcon/etc/systemd/system/falcon.service

Falcon itself now automatically restarts failed child processes too, and hopefully this paves the way for graceful restart/reloading of configuration.

Daemonization of a process can be done by an external tool very easily, e.g. `start-stop-daemon`, or even something like https://github.com/ioquatix/process-daemon - there is no intrinsic reason why it needs to be built into the falcon code base itself.

That being said, I'm open to ideas.

**Comment by ioquatix** [comment]
I'm working on `falcon virtual` which supports this use case. However, I don't believe implementing demonisation into falcon is the right approach, there are plenty of tools that let you achieve that already (e.g. `systemd`). Even despite that, `falcon` supports rolling restarts so in theory most of the functionality you want is there. Once `falcon virtual` matures, there should be good examples of how to integrate this.
