### ISSUE TITLE
API for instantiating server

### ISSUE THREAD

**Issue by WA9ACE** [socketry/falcon#58]
Currently it appears most of the grunt work for producing a functioning falcon server resides in `lib/falcon/command/serve.rb` which is handled by a command line invocation library.

It would be extremely useful to have an API level interface for creating an instance of a falcon server similar to what's available in the likes of WEBrick for example

`Rack::Handler::WEBrick.run(CustomRackApplication.new, Port: 3000, Logger: SomeCustomLogger)`

**Comment by WA9ACE** [comment]
I can have a PR out for this fairly quickly if this is something that would be accepted.

**Comment by ioquatix** [comment]
If you want to use falcon in this way, do it like this:

```ruby
require 'falcon/command'

serve = Falcon::Command::Serve["--port", "9000", parent: Falcon::Command::Top[]]

serve.call
```

Does that solve your problem?

**Comment by WA9ACE** [comment]
Not completely, this still tries to load rack applications from a config.ru, so it's not completely self contained.

**Comment by ioquatix** [comment]
Let me see how we can fix tbis

**Comment by ioquatix** [comment]
You should just directly use `Falcon::Server` and host it in whatever container you want. Here is an example of how to do it: 

https://github.com/socketry/falcon/blob/master/spec/falcon/server_context.rb
