### ISSUE TITLE
Unable to reload falcon through kill -HUP

### ISSUE THREAD

**Issue by ryudoawaru** [socketry/falcon#60]
Example:

```
[~/RailsPrjs/FXEnroll] (master) 0h19m $ falcon serve -b http://localhost:22222
 8.67s: #<Falcon::Endpoint http://localhost:22222/>
      | Falcon taking flight! Using Async::Container::Forked {:count=>4}
      | - To terminate: Ctrl-C or kill 40603
 8.68s: #<Async::Container::Forked::Instance:0x00007ffa1e2aa7b8>
      | - Per-process status: kill -USR1 40831
 8.69s: #<Async::Container::Forked::Instance:0x00007ffa1e29b970>
      | - Per-process status: kill -USR1 40832
 8.69s: #<Async::Container::Forked::Instance:0x00007ffa1e2ca5b8>
      | - Per-process status: kill -USR1 40833
  8.7s: #<Async::Container::Forked::Instance:0x00007ffa19f9d6a0>
      | - Per-process status: kill -USR1 40834
```

And try to send HUP signal

```
 kill -HUP 40603
```

Then

```
Hangup: 1
```

and won't restart.

Is it normal?

**Comment by ioquatix** [comment]
I am going to investigate this issue. The main point is process management, and up until now `falcon serve` has mostly been for development environment. Managing multiple processes is more complex and I hope to make this simple for end user with canonical defaults.

**Comment by ioquatix** [comment]
`falcon serve` now supports rolling restarts, by killing the child process. There is no built in way to do this yet, but you can just use `kill`. Maybe in the future we can automate this. `falcon virtual` supports `falcon supervisor restart`.
