### ISSUE TITLE
Streaming upload

### ISSUE THREAD

**Issue by pschrammel** [socketry/falcon#62]
Hi,
perhaps I missed something but is it possible to have a (perhaps not quite rack compliant) streaming upload? 
Most ruby https servers stream to a file/StringIO and then pass that into the rack stack. This might be okay for small bodies but developing fileservers this way is a pain (local storages have to be huge and moving copying files is necessary).
So the question:
1. is it possible?
2. how?
3. if not, what needs to be done (as far as I know hijack was invented for this kind of things)

THX

**Comment by ioquatix** [comment]
Yes it already works. Use `rack.input` like normal. It's streaming.

**Comment by ioquatix** [comment]
Here is the implementation: https://github.com/socketry/falcon/blob/master/lib/falcon/adapters/input.rb

Maybe we should make an example showing it working.

**Comment by pschrammel** [comment]
thx an example would be nice.
