### ISSUE TITLE
Reuse port missing and breaking Linux binding

### ISSUE THREAD

**Issue by destructobeam** [socketry/falcon#66]
Somewhere between version 0.27.0 and 0.33.0 the --reuse-port option was removed, which is breaking binding on Linux as it is erroring with a port already in use error. However it is still in the README.

Have tried with --threaded, which I thought would work as I would think it is just using one process, but I'm still getting the same error.

**Comment by ioquatix** [comment]
Yes, this was removed, can you explain what process you already have bound? Or is falcon binding to the same port causing problems?

I will review this week.

**Comment by destructobeam** [comment]
Yeah, no other processes using that port, just Falcon I assume trying to use the port for multiple forks and failing.

**Comment by ioquatix** [comment]
That's a bit weird. I'm right in the middle of refactoring HTTP/2 support, once that's sorted I can take a look at this.

**Comment by destructobeam** [comment]
Thanks, do you know off top what version the reuse option was removed in? Will pin to the previous version in the meantime.

**Comment by ioquatix** [comment]
Try v0.31.0

**Comment by ioquatix** [comment]
Just FYI, I'm a move fast and break shit kind of developer. I'm want this code to be stable, but my main priority while in 0.x is to get everything working really well. So, stuff is likely to break, and thus I suggest you pin versions, even to point releases, if it's working well for your use case.

**Comment by destructobeam** [comment]
Thanks, yeah I know, not really concerned about breakages at the moment as still in early development on the project I’m using this and async-websocket on.

I figure Linux support is probably pretty useful though, so happy to keep testing this stuff as you go if you don’t mind the feedback every now and then?

**Comment by ioquatix** [comment]
Yes feedback is great

**Comment by ioquatix** [comment]
Can you please try with the latest release and open a new ticket if the problem persists. There is no need for reuse port unless some other process is already using the port, in which case that's probably an issue with your environment.
