### ISSUE TITLE
Runtime invocation of pry and irb

### ISSUE THREAD

**Issue by stephaniewilkinson** [socketry/falcon#73]
Hi!

I can't get `binding.pry` or `binding.irb` to work with falcon. It stops the app at the point of binding, but you can't use the REPL.

To reproduce, here's a `config.ru` with `binding.irb`:
`
run -> _env { [200, {}, [binding.irb, 'Hello World']] }`

**Comment by picatz** [comment]
👋 Hello!

I am able to reproduce this problem using the default `falcon serve` command.

By default Falcon will use forked mode, which can be manually specified using the `--forked` flag. In this mode the STDIN of our shell doesn't seem to be communicated to the various child processes Falcon spawns where the pry/irb REPL is started.

To get avoid this behavior for REPL-friendly testing, you can use threaded mode via the `--threaded` flag.

```console
$ falcon serve --threaded
...
From: config.ru @ line 3 :

    1: require 'pry'
    2: 
 => 3: run -> _env { [200, {}, [binding.irb, 'Hello World']] }

2.6.3 :001 > puts "hello"
hello
 => nil
```

**Comment by ioquatix** [comment]
Thanks @picatz you are awesome!

**Comment by ioquatix** [comment]
This makes me think that falcon needs some kind of wiki, knowledge-base, or how to guide.

We could use the github wiki, make some custom documentation (e.g. github docs) or something else (e.g. gitbooks).

I suspect that we could focus on:

- Using falcon for development.
- Using falcon for production.

Maybe exploring the structure can be a good idea.

I'm okay with using github wiki, but I don't like being tied into a specific system/platform.

**Comment by stephaniewilkinson** [comment]
Thanks @picatz! This is exactly what I needed.

As far as docs, the best I've seen the GitHub wiki used was for http.rb: https://github.com/httprb/http/wiki.
