### ISSUE TITLE
How to read input body stream asynchronously?

### ISSUE THREAD

**Issue by tonytonyjan** [socketry/falcon#74]
I am building an application to handle large data. So far I have figured out how to write data to reponse body using `Async::HTTP::Body::Writable`.

Unfortunately, `rack.input` is not asynchronous. If uploading a certain file takes 5s and 2 requests occors simultaneously, with only one falcone instance, the second request would take 10s to finish uploading while the first one only takes 5s.

I guess the solution would be something to do with the intergration between `Async::HTTP::Body::Writable` and `rack.input` but I really don't know how since I am a newbie of falcon.

What is the right way to do this? Is there any workaround?

**Comment by ioquatix** [comment]
It should be asynchronous, can you give me a short repro?

**Comment by tonytonyjan** [comment]
I found that Flacon does make `rack.input` asynchronous.

I was just confused because I was uplaoding files with single machine, and exhausted its IO resources.

Sorry for bothering :(
