### ISSUE TITLE
Further improvements to `Input`

### ISSUE THREAD

**Issue by ioquatix** [socketry/falcon#8]
As discussed here: https://github.com/socketry/falcon/pull/4

**Comment by ioquatix** [comment]
@janko-m Is your plan to add an `outbuf` to every `Async::HTTP::Body#read` call?

How does this work in the presence of decompression/compression?

**Comment by ioquatix** [comment]
@tarcieri said:

> Note that this is exactly the sort of use case NIO::ByteBuffer is for:

> https://github.com/socketry/nio4r/wiki/Byte-Buffers

> For copy_stream-style use cases where copy_stream won't suffice, it can avoid any allocations as well as the insanity of MRI I/O.

**Comment by ioquatix** [comment]
@janko-m said:

> @ioquatix You're absolutely right and your idea sounds very compelling, I would like to have specs for how much memory Falcon::Adapters::Input allocates, especially because my use case is sensitive to extra allocations.
>
> I like how simple your RSpec matcher for checking open file descriptors is, we could do something similar for string allocations. It would need to also detect when strings are deallocated with String#clear, hopefully ObjectSpace already handles that.
> 
> I think it would be useful to release it as a separate gem, since it wouldn't be related to async (I can think of couple of other gems where I would like to add memory usage specs).
> 
> Note that this is exactly the sort of use case NIO::ByteBuffer is for
> @tarcieri Hmm, I'm not really sure how NIO::ByteBuffer could help us here. The problem are mainly string allocations that happen before we retrieve the chunk of string we want to return (or replace/append to the output buffer). To be clear, I'm talking now only about implementing the #read method, not how that method is used.

**Comment by janko-m** [comment]
> Is your plan to add an `outbuf` to every `Async::HTTP::Body#read` call?

Yes, that's the plan. As I see it at the moment, we would need to provide an `outbuf` all the way to `Async::IO::Stream#read_partial`, but I'll have a better idea once I get a better understanding of the code.

I just need a bit time to unwrap the fact that the native `Socket` is wrapped by `Async::IO::Socket`, then wrapped by `Async::IO::Stream`, then wrapped by `Async::HTTP::Body`, which is wrapped by `Falcon::Adapters::Input` 😃. To be clear, I love the design, I'm surprised by how easy I can navigate around considering I'm reading it for the first time. I just need to note all places where chunks of request body are being allocated.

> How does this work in the presence of decompression/compression?

I'm not yet sure. Where does (de)compression appear in Falcon/async-http/async-io?

> I've added a separate issue for tracking memory allocations.

Thanks!

**Comment by ioquatix** [comment]
> I'm not yet sure. Where does (de)compression appear in Falcon/async-http/async-io?

- https://github.com/socketry/async-http/blob/master/lib/async/http/body/inflate.rb
- https://github.com/socketry/async-http/blob/master/lib/async/http/body/deflate.rb

**Comment by ioquatix** [comment]
While I may change my position, just so you know, I'm hesitant to change the API in this way, in the sense that I think it makes it more complex for users, and honestly, the Ruby VM should just do escape analysis or uses a buffer pool for managing allocations.

I'm fully invested in solving this issue. I just want to make sure that we consider all options. I get a good feeling about your domain knowledge in this regard, so I'll probably end up deferring to your judgement, but I also like the simplicity of the current design.

**Comment by ioquatix** [comment]
![69411cd5e85218373d393a7cd40a3d1a](https://user-images.githubusercontent.com/30030/41183185-6a306e2e-6bcd-11e8-8495-7f27858824be.jpg)

**Comment by ioquatix** [comment]
FYI, I've added `limit_allocations`, here is an example:

https://github.com/socketry/async-io/blob/500af20d445f340aeee90d0e5e832549eb2eb103/spec/async/io/stream_spec.rb#L64-L71

**Comment by ioquatix** [comment]
@tarcieri One issue with using ByteBuffers is that they aren't strings.

A lot of APIs expect strings. I know strings are the shit for data. Literally. But that's just how it is, for better or for worse.

Is there some way (perhaps I missed it) for getting the contents of a byte buffer as an immutable/frozen string (ideally zero copy). It only needs to exist for the life time of the byte buffer remaining unflipped. Thoughts?

**Comment by ioquatix** [comment]
I am going to close this issue as the input adaptor has been improved to handle streaming better.

I am happy to discuss further changes but they should be backed by a PR.
