### ISSUE TITLE
rack#1181 merged?

### ISSUE THREAD

**Issue by tleish** [socketry/falcon#83]
Readme states:

> Alternatively run RACK_HANDLER=falcon rails server to start the server (at least, until [rack#1181](https://github.com/rack/rack/pull/1181) is merged).

[rack#1181](https://github.com/rack/rack/pull/1181) is now merged, what should this say now?

**Comment by ioquatix** [comment]
It’s not released yet?

**Comment by olleolleolle** [comment]
This Issue duplicates already-reported #81.

**Comment by olleolleolle** [comment]
Hope this helps! Thanks for looking out for outdated content!
