### ISSUE TITLE
Slow Startup with ruby-debug-ide Debug gem

### ISSUE THREAD

**Issue by tleish** [socketry/falcon#84]
When running falcon on Rubymine IDE using the [ruby-debug-ide](https://github.com/ruby-debug/ruby-debug-ide) gem it takes 10 to 15 seconds to startup.  Note that the other non-blocking Ruby web server I tested took approximately 3 seconds.

Once falcon is started, debug performance is as expected.

I like falcon (and Rubymine) and hope the startup performance can be improved at some point.

**Comment by ioquatix** [comment]
Happy to help but can you provide some more information? Are you able to capture profile or maybe provide any idea why it’s so slow?

**Comment by tleish** [comment]
I believe I've determined it's because of the default number of instances to start.  The other server I was testing only ran 1, whereas falcon ran multiple.  I tried running with the option `--count 1` and debugging start times were about the same.

Now that I've set this to 1, that setting has been cached somewhere and to get it to be more I have to reset it.  What is the default and where is this setting cached?

Note: I also tried running with `--forks 1` and `--threads 1`  but got errors in doing this.  Either:

```
lib/async/container/forked.rb:60:in `spawn': unknown keyword: threads (ArgumentError)
```
or
```
lib/async/container/forked.rb:60:in `spawn': unknown keyword: forks (ArgumentError)
```
Perhaps I'm misunderstanding this setting.

**Comment by ioquatix** [comment]
Those options are only for hybrid mode

**Comment by tleish** [comment]
Thanks for the explanation
-- 

-Thomas

**Comment by ViugiNick** [comment]
@tleish Could you please specify ruby-debug-ide and debase gems versions you are using?

**Comment by tleish** [comment]
@ViugiNick 
- ruby-debug-ide 0.8.0.beta6
- debase 0.3.0.beta7

Both are auto-installed with Rubymine

**Comment by ViugiNick** [comment]
@tleish Could you please try one of the latest RubyMine EAPs (and ruby-debug-ide 0.8.0.beta18, debase 0.3.0.beta18 which are bundled there)

**Comment by ioquatix** [comment]
@ViugiNick thanks for stepping in.

@tleish I've reopened this issue so we can track the suggestions here. Once you are happy that this is definitely fixed, feel free to close it again.

**Comment by tleish** [comment]
What is falcons default settings for number of forks?
-- 

-Thomas

**Comment by ioquatix** [comment]
The number of CPU cores.

**Comment by tleish** [comment]
Sorry, I meant to ask what is the default number for "---count"?

**Comment by tleish** [comment]
Ah, 8... sorry.  Just read the README

**Comment by tleish** [comment]
Just tested using ruby-debug-ide 0.8.0.beta18, debase 0.3.0.beta18.  It started up so mach faster than before that I wondered if I might have made a mistake.  Verified debugger was working and tested multiple time.

@ViugiNick - thanks for the tip.

Now we just need to get Rubymine to include Falcon as one of the supported Rack servers.
https://youtrack.jetbrains.com/issue/RUBY-22808

Closing this issue now.

**Comment by ioquatix** [comment]
Thanks for everyone’s effort!

**Comment by mscrivo** [comment]
How does one use these newer versions of ruby-debug-ide/debase? I'm running the latest Rubymine and it's using these versions:

`Fast Debugger (ruby-debug-ide 0.7.3, debase 0.2.5.beta2, file filtering is supported) listens on 0.0.0.0:55192`

and startup is painfully slow.
