### ISSUE TITLE
Crashes on stress test with Errno::EMFILE: Too many open files

### ISSUE THREAD

**Issue by tleish** [socketry/falcon#85]
To reproduce, run 1 instance of falcon using the following command:

`falcon serve --bind http://localhost:9000 --count 1`

Then test using siege

```
$siege http://localhost:9000/ping
HTTP/1.1 200     0.17 secs:      45 bytes ==> GET  /v1/ship/ping
HTTP/1.1 200     0.18 secs:      45 bytes ==> GET  /v1/ship/ping
HTTP/1.1 200     0.18 secs:      45 bytes ==> GET  /v1/ship/ping
HTTP/1.1 200     0.18 secs:      45 bytes ==> GET  /v1/ship/ping
...
HTTP/1.1 200     0.18 secs:      45 bytes ==> GET  /v1/ship/ping
HTTP/1.1 200     0.19 secs:      45 bytes ==> GET  /v1/ship/ping
HTTP/1.1 200     0.18 secs:      45 bytes ==> GET  /v1/ship/ping
[error] socket: read error Connection reset by peer sock.c:539: Connection reset by peer
```
falcon log files
```
error: #<Async::Task:0x3fedfd451818 accepting connections #<Addrinfo: 127.0.0.1:9000 TCP> [fd=19] (failed)> [pid=79896] [2019-11-08 21:16:05 -0700]
|   Errno::EMFILE: Too many open files - accept(2)
|     ruby/2.6.5/lib/ruby/2.6.0/socket.rb:593 in `__accept_nonblock'
|     ruby/2.6.5/lib/ruby/2.6.0/socket.rb:593 in `accept_nonblock'
|     ruby/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.27.0/lib/async/io/generic.rb:214 in `async_send'
|     ruby/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.27.0/lib/async/io/socket.rb:126 in `accept'
|     ruby/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.27.0/lib/async/io/socket.rb:103 in `accept_each'
|     ruby/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.27.0/lib/async/io/shared_endpoint.rb:102 in `block in accept'
|     ruby/2.6.5/lib/ruby/gems/2.6.0/gems/async-io-1.27.0/lib/async/io/shared_endpoint.rb:74 in `block (2 levels) in bind'
|     ruby/2.6.5/lib/ruby/gems/2.6.0/gems/async-1.23.0/lib/async/task.rb:255 in `block in make_fiber'
```

**Comment by ioquatix** [comment]
Did you read the documentation?

**Comment by ioquatix** [comment]
Sorry, I thought this was easier to find.

But there is some documentation here: https://github.com/socketry/async-dns/blob/ca4fe0f662d21bba211c082af4eb4b1f9004788b/README.md#file-handle-limitations

**Comment by ioquatix** [comment]
Related issue with other suggestions: https://github.com/socketry/async-io/issues/4

**Comment by tleish** [comment]
Sorry, I didn't read documentation of falcons gem dependencies.  It might be worth combining the documentation in one place at some point.

Thanks for pointing me to the answer.

**Comment by ioquatix** [comment]
I shouldn't have been so direct, I just woke up. `ulimit` is kind of an important thing to be aware of when running benchmarks, as it's going to affect every server you test.

**Comment by ioquatix** [comment]
Let me know if you have any other issues.

**Comment by tleish** [comment]
No worries, I've been peppering you with questions these past few days.  You've been a champion at responding, which is one of the main reasons I'm considering falcon.

**Comment by ioquatix** [comment]
There is one other limit which you might need to consider, the number of vm mappings allowed by the kernel... it can cause mmap to fail... it should be relatively graceful... but it's not ideal either :)
