### ISSUE TITLE
Support Ruby 2.3

### ISSUE THREAD

**Issue by BMorearty** [socketry/falcon#89]
I see that Ruby 2.3 was in the Travis files for async and async-http. Any chance Falcon could also support 2.3 or is there a blocker?

**Comment by ioquatix** [comment]
I am planning to drop 2.3 across all gems soon. It's already EOL. What's your use-case?

**Comment by BMorearty** [comment]
It turns out we don't need it after all.... Airbnb has a service on which I was going to test Falcon and the service uses 2.3. But I asked the lead maintainer of the service and he's going to upgrade it it to 2.6.

**Comment by ioquatix** [comment]
Even thought you closed this issue can you comment on what kind of strategy makes He most sense?

**Comment by BMorearty** [comment]
Background: I'm not talking about any one particular company, but I've found it's common for businesses to deprioritize language upgrades, leaving them stuck on older versions unless engineers want to take initiative on their own time to do upgrades. Ruby upgrades are pretty straightforward but Rails upgrades are not, and each version of Rails only supports a limited set of Ruby versions. So if a business has a lot of Rails services, they can easily end up behind. A couple of engineers might take the initiative to upgrade a couple of services, but that still leaves all the other services out.

I understand Ruby core has no responsibility to support such use cases. Nor do gem maintainers. At the same time, if it's low-overhead to keep testing older Ruby versions in Travis for a gem, I don't see any reason not to. It can help some users.
