### ISSUE TITLE
Falcon::Adapters::Input doesn't have #empty? method

### ISSUE THREAD

**Issue by senid231** [socketry/falcon#94]
in case of running rack application `env['rack.input']` is a `Falcon::Adapters::Input` with body `Protocol::HTTP1::Body::Fixed` which has `#empty?` method.
Since body is not rewindable it's the only way to define if it has content or not.

this issue related to problem in general
https://github.com/rack/rack/issues/1148

this issue related to specific problem when using `falcon` `sinja` gems together
https://github.com/mwpastore/sinja/issues/19

not sure if it works correctly with http2 or not

**Comment by ioquatix** [comment]
We can try to fix this for Rack 3 since it requires an updated interface for `rack.input` IIRC.

**Comment by ioquatix** [comment]
This should be fixed: https://github.com/socketry/protocol-rack/blob/ec318a60b894553633a43e62d78de07153274cdd/lib/protocol/rack/input.rb#L84-L87

If there are further issues, please feel free to re-open on the `protocol-rack` repository.
