### ISSUE TITLE
incoming connection #<Addrinfo: [::1]:52103 TCP causes NoMethodError: undefined method `headers'

### ISSUE THREAD

**Issue by deepj** [socketry/falcon#97]
I'm on macOS Mojave and use the latest Falcon and I'm not sure what's exactly causing the connections but I'm getting this error

```
 6m54s    error: #<Async::Task:0x1bddc incoming connection #<Addrinfo: [::1]:52103 TCP> [fd=26] (failed)> [pid=24051] [2020-01-15 16:21:41 +0100]
               |   NoMethodError: undefined method `headers' for nil:NilClass
               |   → ~/.gem/ruby/2.7.0/gems/protocol-http-0.13.0/lib/protocol/http/content_encoding.rb:47 in `call'
               |     ~/.gem/ruby/2.7.0/gems/protocol-http-0.13.0/lib/protocol/http/middleware.rb:40 in `call'
               |     ~/.gem/ruby/2.7.0/gems/async-http-0.50.0/lib/async/http/server.rb:64 in `block in accept'
               |     ~/.gem/ruby/2.7.0/gems/async-http-0.50.0/lib/async/http/protocol/http1/server.rb:58 in `each'
               |     ~/.gem/ruby/2.7.0/gems/async-http-0.50.0/lib/async/http/server.rb:53 in `accept'
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.1/lib/async/io/socket.rb:99 in `block in accept_each'
               |     ~/.gem/ruby/2.7.0/gems/async-io-1.27.1/lib/async/io/socket.rb:137 in `block in accept'
               |     ~/.gem/ruby/2.7.0/gems/async-1.24.1/lib/async/task.rb:256 in `block in make_fiber'
```

I guess this would not have happened :)

**Comment by ioquatix** [comment]
That is very weird, I will take a look.

**Comment by ioquatix** [comment]
Can you try the latest version, also can you tell me what client you are using?

**Comment by deepj** [comment]
@ioquatix Try it later today and let you know. I use standard Firefox as a client

**Comment by olleolleolle** [comment]
Here's a dumb macOS guess: [Xsan](https://en.wikipedia.org/wiki/Xsan) operates on that port range.

**Comment by ioquatix** [comment]
I guess it's weird it ever got to that point (nil headers). However, the header parsing for HTTP/1.x is more robust in recent versions... hopefully that will help.

**Comment by deepj** [comment]
@ioquatix Sorry for the delay. My country declared state of emergency due to COVID-19, closed borders and banned many activities yesterday. It was a bit hectic day.

Yes, it seems it helped. But a new problem occurred while establishing websocket connection (the application uses actioncable). I can report it.

BTW and offtopic: Is there any guide how to set Falcon and Rails app for production? I couldn 't find any documentation to it.

**Comment by deepj** [comment]
@ioquatix I guess this issue can be closed. I haven't seen any issue like this with the latest changes in Falcon
